---
- name: File Module
  hosts: all
  tasks:
    - name: Create a file
      file:
        path: /home/ansible/ansible_file.txt
        state: touch
        owner: root
        group: root
        mode: 770
