---
- name: kill a process on remote server
  hosts: Node1

  tasks:
    - name: kill nginx
      ignore_errors: yes
      shell: "pgrep nginx | xargs kill"
    - name: start nginx
      service: 
        name: nginx
        state: started
