---
- name: Build and deploy docker container
  hosts: localhost 
  gather_facts: false
    # become: true
  tasks:
    - name: test connection
      ping:
    - name: copy files to remote server
      #become: true
      copy:
        src: /var/lib/jenkins/workspace/ansible-jenkins-pipeline/
        dest: /home/ansible/project/
          # remote_src: true
    - name: Building Docker Image
      shell: docker build -t test1 /home/ansible/project/ 
    - name: run container
      shell: docker run --name test -p 81:80 test1
