---
- name: Copy files to Node2
  hosts: Node2
  tasks:
    - name: Copy Files
      copy:
        src: /home/ansible/sample.txt
        dest: /home/ec2-user/
        owner: ec2-user
        group: ec2-user
        mode: ugo=rw
        backup: true
