---
- name: Run Script
  hosts: all
  tasks:
    - name: copy test.sh to remote
      copy:
        src: /home/ansible/ansible/run_script/test.sh
        dest: /home/ansible/test.sh
        owner: ansible
        group: ansible
        mode: u+rwx 
    - name:   Change directory first and then Run a script
      shell: ./test.sh >> test.log
      args:
        chdir: /home/ansible
        creates: test.log
      register: result
    - name: print output
      debug: 
        var: result
