--- 
- name: Install and start nginx
  hosts: localhost
  vars:
    - app: nginx
  tasks: 
  - name: install nginx
    yum:
      name: "{{ app }}"
      state: present
    tags: install
  - name: start nginx
    service:
      name: "{{ app }}"
      state: started
      enabled: true
    tags: start
