--- 
- name: Install and start nginx
  hosts: localhost
  tasks: 
  - name: install nginx
    yum:
      name: nginx
      state: present
    tags: install
  - name: start nginx
    service:
      name: nginx
      state: started
      enabled: true
    tags: start
